#!/bin/bash
. ~/.config/waybar/utils/hyprv.conf
. ~/.config/.resources/variables.conf

update_theme() {
	#set the xfce and GTK theme
	xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"
	gsettings set org.gnome.desktop.interface icon-theme "Adwaita$SWITCHTO"

	xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
	gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
}

restart_waybar() {
	pkill waybar
	waybar &
}

set_current_background() {
	if [[ ! -z "$BG_PATH" ]]; then
		#set the current background
		swww img ~/.dotfiles/.config/.resources/images/Kurumi_bg.jpg
	else
		swww img $BG_PATH
	fi
}

if [[ "$1" == "restart" ]]; then
	restart_waybar
elif [[ "$1" == "setbg" ]]; then
	$CONFIG_ROOT/.resources/scripts/set-bg
	update_theme
	restart_waybar
fi

TOOLTIP="Default Keybinds\n\n\
󰘳 + A = Toggle Maximize\n\
󰘳 + F = Toggle Fullscreen\n\
󰘳 + V = Toggle Float\n\
󰘳 + T = Toggle Split\n\\n\
󰘳 + E = File Manager\n\
󰘳 + Q = Start Kitty\n\
󰘳 + F4 = Close Window\n\n\
󰘳 + M = Logout menu\n\
󰘳 + S = Screenshot\n\
󰘳 + SPACE = App Launcher (wofi)\n\
ALT + V = Open clipboard manager"

echo '{"tooltip": "'$TOOLTIP'"}'
